(function(){
    var modules={
        "panel-main-cupid":    	        {url:"$H/m/panel-main.html",router:1},
        "panel-child-cupid":              {url:"$H/m/panel-child.html"},
        "panel-library-cupid":    		{url:"$H/m/panel-library.html",router:1},
        "panel-export-screening-cupid":   {url:"$H/m/export/panel-export-screened.html",router:1},
        "panel-export-enrolled-cupid":    {url:"$H/m/export/panel-export-enrolled.html",router:1},
        "export-data":		                {url:"$H/m/export/export-data.html",Table:"export-cupid",form_module:"export-form"},
        "export-form":		                {url:"$H/m/export/export-form.html",Table:"export-cupid"},
        
        "participant-data":   		        {url:"$H/m/participant/participant-data.html",Table:"cupid-participant",form_module:"participant-form",router:1,
                                                child_panel:"panel-child-cupid",
                                                questionnaire_setup:"online-questionnaire-setup-cupid",
                                                online_questionnaire:"online-questionnaire-app-cupid",
                                                participant_id:{field1:"Participant"},
                                                participant_export:"ID,Subject_ID,Screening_Number,Randomisation_Number,Subject_Initials,Gender,DOB"
                                            },
        "participant-form":   		        {url:"$H/m/participant/participant-form.html",Table:"cupid-participant"},

        "online-questionnaire-setup-cupid": {url:"$H/m/oq-setup.html",Table:"cupid-participant"},
        "online-questionnaire-app-cupid":   {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"cupid-notes",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"cupid-notes"},

        "randomisation-table-data-cupid":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-cupid",form_module:"randomisation-table-form-cupid"},
        "randomisation-table-form-cupid":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-cupid"},
//General
        "demographics-data-cupid":		{url:"$H/m/library/demographics-data.html",Table:"demographics-cupid",form_module:"demographics-form-cupid",task_name:"General Information - Demographics"},
        "demographics-form-cupid":		{url:"$H/m/library/demographics-form.html",Table:"demographics-cupid",task_name:"General Information - Demographics"},
//Unscheduled
        "adverse-event-data-cupid":		{url:"$H/m/library/adverse-event-data.html",Table:"adverse-event-cupid",form_module:"adverse-event-form-cupid",task_name:"Unscheduled - Adverse Event"},
        "adverse-event-form-cupid":		{url:"$H/m/library/adverse-event-form.html",Table:"adverse-event-cupid",task_name:"Unscheduled - Adverse Event"},
        "file-notes-data-cupid":		{url:"$H/m/library/file-notes-data.html",Table:"file-notes-cupid",form_module:"file-notes-form-cupid",task_name:"Unscheduled - File Notes"},
        "file-notes-form-cupid":		{url:"$H/m/library/file-notes-form.html",Table:"file-notes-cupid",task_name:"Unscheduled - File Notes"},
//Screening
        "date-s-data-cupid":                {url:"$H/m/library/date-data.html",Table:"date-s-cupid",form_module:"date-s-form-cupid",task_name:"Screening - Visit Date"},
        "date-s-form-cupid":                {url:"$H/m/library/date-form.html",Table:"date-s-cupid",task_name:"Screening - Visit Date"},
        "anthropometry-s-data-cupid":       {url:"$H/m/library/anthropometry-data.html",Table:"anthropometry-s-cupid",form_module:"anthropometry-s-form-cupid",task_name:"Screening - Anthropometry"},
        "anthropometry-s-form-cupid":       {url:"$H/m/library/anthropometry-form.html",Table:"anthropometry-s-cupid",task_name:"Screening - Anthropometry"},
        "medical-history-s-data-cupid":       {url:"$H/m/library/medical-assessment-data.html",Table:"medical-history-s-cupid",form_module:"medical-history-s-form-cupid",task_name:"Screening - Medical history)"},
        "medical-history-s-form-cupid":       {url:"$H/m/library/medical-assessment-form.html",Table:"medical-history-s-cupid",task_name:"Screening - Medical history"},
        "isi-pre-s-data-cupid":       {url:"$H/m/library/isi-pre-data.html",Table:"isi-pre-s-cupid",form_module:"isi-pre-s-form-cupid",task_name:"Screening - ISI from Pre-screening"},
        "isi-pre-s-form-cupid":       {url:"$H/m/library/isi-pre-form.html",Table:"isi-pre-s-cupid",task_name:"Screening - ISI from Pre-screening"},
        "ess-s-data-cupid":       {url:"$H/m/library/ess-data.html",Table:"ess-s-cupid",form_module:"ess-s-form-cupid",task_name:"Screening - Epworth Sleepiness Scale (ESS)"},
        "ess-s-form-cupid":       {url:"$H/m/library/ess-form.html",Table:"ess-s-cupid",task_name:"Screening - Epworth Sleepiness Scale (ESS)"},
        "hads-s-data-cupid":       {url:"$H/m/library/hads-data.html",Table:"hads-s-cupid",form_module:"hads-s-form-cupid",task_name:"Screening - Hospital Anxiety and Depression Scale (HADS)"},
        "hads-s-form-cupid":       {url:"$H/m/library/hads-form.html",Table:"hads-s-cupid",task_name:"Screening - Hospital Anxiety and Depression Scale (HADS)"},
        "phq9-s-data-cupid":       {url:"$H/m/library/phq-data.html",Table:"phq-s-cupid",form_module:"phq9-s-form-cupid",task_name:"Screening - Patient Health Questionnaire-9 (PHQ-9)"},
        "phq9-s-form-cupid":       {url:"$H/m/library/phq-form.html",Table:"phq-s-cupid",task_name:"Screening - Patient Health Questionnaire-9 (PHQ-9)"},
        "ecg-report-s-data-cupid":       {url:"$H/m/library/file-upload-data.html",Table:"ecg-report-s-cupid",form_module:"ecg-report-s-form-cupid",task_name:"Screening - ECG Report Data Upload"},
        "ecg-report-s-form-cupid":       {url:"$H/m/library/file-upload-report-form.html",Table:"ecg-report-s-cupid",task_name:"Screening -ECG Report Data Upload"},
        "inclusion-exclusion-s-data-cupid":       {url:"$H/m/library/inclusion-exclusion-data.html",Table:"inclusion-exclusion-s-cupid",form_module:"inclusion-exclusion-s-form-cupid",task_name:"Screening - Inclusion / Exclusion Criteria Checklist"},
        "inclusion-exclusion-s-form-cupid":       {url:"$H/m/library/inclusion-exclusion-form.html",Table:"inclusion-exclusion-s-cupid",task_name:"Screening - Inclusion / Exclusion Criteria Checklist"},
        "urin-drug-screen-s-data-cupid":       {url:"$H/m/library/urin-drug-screen-data.html",Table:"urin-drug-screen-s-cupid",form_module:"urin-drug-screen-s-form-cupid",task_name:"Screening - Urinary Drug Screen"},
        "urin-drug-screen-s-form-cupid":       {url:"$H/m/library/urin-drug-screen-form.html",Table:"urin-drug-screen-s-cupid",task_name:"Screening - Urinary Drug Screen"},
        "psg-s-data-cupid":                {url:"$H/m/library/psggrr-data.html",Table:"psg-s-cupid",form_module:"psg-s-form-cupid",task_name:"Screening - Polysomnography (PSG) report"},
        "psg-s-form-cupid":                {url:"$H/m/library/psggrr-form.html",Table:"psg-s-cupid",task_name:"Screening - Polysomnography (PSG) report"},
//Other
        "medical-history-data-cupid":	    {url:"$H/m/library/medical-history-data.html",Table:"medical-history-cupid",form_module:"medical-history-form-cupid",task_name:"Other - Medical History"},
        "medical-history-form-cupid":	    {url:"$H/m/library/medical-history-form.html",Table:"medical-history-cupid",task_name:"Other - Medical History"},
//Blood Analysis
        "blood-analysis-data-cupid":       {url:"$H/m/library/upload-file-data.html",Table:"blood-analysis-cupid",form_module:"blood-analysis-form-cupid",task_name:"Blood Analysis Data Upload"},
        "blood-analysis-form-cupid":       {url:"$H/m/library/upload-file-form.html",Table:"blood-analysis-cupid",task_name:"Blood Analysis Data Upload"},
//Urinary
        "urinary-analysis-data-cupid":       {url:"$H/m/library/upload-file-data.html",Table:"urinary-analysis-cupid",form_module:"urinary-analysis-form-cupid",task_name:"Urinary Analysis Data Upload"},
        "urinary-analysis-form-cupid":       {url:"$H/m/library/upload-file-form.html",Table:"urinary-analysis-cupid",task_name:"Urinary Analysis Data Upload"},
//Practice
        "word-pairs-pre-set1-practice":	    {url:"$H/m/word-pairs/evening-wordpairs-set1-practice.html"},
        "word-pairs-pre-set2-practice":	    {url:"$H/m/word-pairs/evening-wordpairs-set2-practice.html"},
        "word-pairs-pre-set3-practice":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-practice.html"},
//Session 1
        "ksd-pts1-data-cupid":                {url:"$H/m/library/ksd-data.html",Table:"ksd-pts1-cupid",form_module:"ksd-pts1-form-cupid",task_name:"Pre-Treatment Session 1 - Karolinska Sleep Diary"},
        "ksd-pts1-form-cupid":                {url:"$H/m/library/ksd-form.html",Table:"ksd-pts1-cupid",task_name:"Pre-Treatment Session 1 - Karolinska Sleep Diary"},
        "actigraphy-pts1-data-cupid":                {url:"$H/m/library/actiwatch-data.html",Table:"actigraphy-pts1-cupid",form_module:"actigraphy-pts1-form-cupid",task_name:"Pre-Treatment Session 1 - Actigraphy data/report"},
        "actigraphy-pts1-form-cupid":                {url:"$H/m/library/actiwatch-form.html",Table:"actigraphy-pts1-cupid",task_name:"Pre-Treatment Session 1 - Actigraphy data/report"},

        "date-tsn1-data-cupid":                {url:"$H/m/library/date-data.html",Table:"date-tsn1-cupid",form_module:"date-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Visit Date"},
        "date-tsn1-form-cupid":                {url:"$H/m/library/date-form.html",Table:"date-tsn1-cupid",task_name:"Treatment Session 1 – Night - Visit Date"},
        "bms-tsn1-data-cupid":                {url:"$H/m/library/bms-data.html",Table:"bms-tsn1-cupid",form_module:"bms-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Brief Medical Screen"},
        "bms-tsn1-form-cupid":                {url:"$H/m/library/bms-form.html",Table:"bms-tsn1-cupid",task_name:"Treatment Session 1 – Night - Brief Medical Screen"},
        "drug-admin-tsn1-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsn1-cupid",form_module:"drug-admin-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Time drug administration and biological collections"},
        "drug-admin-tsn1-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsn1-cupid",task_name:"Treatment Session 1 – Night - Time drug administration and biological collections"},
        "pre-finger-tapping-tsn1-data-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"pre-finger-tapping-tsn1-cupid",form_module:"pre-finger-tapping-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Finger Tapping"},
        "pre-finger-tapping-tsn1-form-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"pre-finger-tapping-tsn1-cupid",task_name:"Treatment Session 1 – Night - Finger Tapping"},
        "poms-t1-tsn1-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t1-tsn1-cupid",form_module:"poms-t1-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t1-tsn1-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t1-tsn1-cupid",task_name:"Treatment Session 1 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t2-tsn1-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t2-tsn1-cupid",form_module:"poms-t2-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "poms-t2-tsn1-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t2-tsn1-cupid",task_name:"Treatment Session 1 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "deq-t1-tsn1-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t1-tsn1-cupid",form_module:"deq-t1-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Drug Effects Questionnaire (DEQ) (T1: Baseline)"},
        "deq-t1-tsn1-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t1-tsn1-cupid",task_name:"Treatment Session 1 – Night - Drug Effects Questionnaire (DEQ) (T1: Baseline)"},
        "deq-t2-tsn1-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t2-tsn1-cupid",form_module:"deq-t2-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "deq-t2-tsn1-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t2-tsn1-cupid",task_name:"Treatment Session 1 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "posture-t1-tsn1-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t1-tsn1-cupid",form_module:"posture-t1-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Posturography (T1: Baseline)"},
        "posture-t1-tsn1-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t1-tsn1-cupid",task_name:"Treatment Session 1 – Night - Posturography (T1: Baseline)"},
        "posture-t2-tsn1-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t2-tsn1-cupid",form_module:"posture-t2-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Posturography (T2: Post Drug Administration)"},
        "posture-t2-tsn1-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t2-tsn1-cupid",task_name:"Treatment Session 1 – Night - Posturography (T2: Post Drug Administration)"},
        "kss-tsn1-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsn1-cupid",form_module:"kss-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsn1-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsn1-cupid",task_name:"Treatment Session 1 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kdt-tsn1-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsn1-cupid",form_module:"kdt-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsn1-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsn1-cupid",task_name:"Treatment Session 1 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "psg-tsn1-data-cupid":                {url:"$H/m/library/psggrr-data.html",Table:"psg-tsn1-cupid",form_module:"psg-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Polysomnography (PSG) report"},
        "psg-tsn1-form-cupid":                {url:"$H/m/library/psggrr-form.html",Table:"psg-tsn1-cupid",task_name:"Treatment Session 1 – Night - Polysomnography (PSG) report"},
        "uds-tsn1-data-cupid":                {url:"$H/m/library/urin-drug-screen-data.html",Table:"uds-tsn1-cupid",form_module:"uds-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Urinary drug screen (UDS)"},
        "uds-tsn1-form-cupid":                {url:"$H/m/library/urin-drug-screen-form.html",Table:"uds-tsn1-cupid",task_name:"Treatment Session 1 – Night - Urinary drug screen (UDS)"},
        "sds-t1-tsn1-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t1-tsn1-cupid",form_module:"sds-t1-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t1-tsn1-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t1-tsn1-cupid",task_name:"Treatment Session 1 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t2-tsn1-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t2-tsn1-cupid",form_module:"sds-t2-tsn1-form-cupid",task_name:"Treatment Session 1 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},
        "sds-t2-tsn1-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t2-tsn1-cupid",task_name:"Treatment Session 1 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},

        "kdt-tsd1-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsd1-cupid",form_module:"kdt-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsd1-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsd1-cupid",task_name:"Treatment Session 1 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kss-tsd1-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsd1-cupid",form_module:"kss-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsd1-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsd1-cupid",task_name:"Treatment Session 1 – Day - Karolinska Sleepiness Scale (KSS)"},
        "driving-tsd1-data-cupid":                {url:"$H/m/library/driving-data.html",Table:"driving-tsd1-cupid",form_module:"driving-tsd1-form-cupid",task_name:"Treatment Session 1 – Day -Driving Simulation Report Upload"},
        "driving-tsd1-form-cupid":                {url:"$H/m/library/driving-form.html",Table:"driving-tsd1-cupid",task_name:"Treatment Session 1 – Day - Driving Simulation Report Upload"},
        "posture-t3-tsd1-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t3-tsd1-cupid",form_module:"posture-t3-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Posturography (T3: Upo Wake)"},
        "posture-t3-tsd1-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t3-tsd1-cupid",task_name:"Treatment Session 1 – Day - Posturography (T3: Upo Wake)"},
        "lseq-tsd1-data-cupid":                {url:"$H/m/library/lseq-data.html",Table:"lseq-tsd1-cupid",form_module:"lseq-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "lseq-tsd1-form-cupid":                {url:"$H/m/library/lseq-form.html",Table:"lseq-tsd1-cupid",task_name:"Treatment Session 1 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "rcsq-tsd1-data-cupid":                {url:"$H/m/library/rcsq-data.html",Table:"rcsq-tsd1-cupid",form_module:"rcsq-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        "rcsq-tsd1-form-cupid":                {url:"$H/m/library/rcsq-form.html",Table:"rcsq-tsd1-cupid",task_name:"Treatment Session 1 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        //"diss-t1-tsd1-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t1-tsd1-cupid",form_module:"diss-t1-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t1-tsd1-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t1-tsd1-cupid",task_name:"Treatment Session 1 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t2-tsd1-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t2-tsd1-cupid",form_module:"diss-t2-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        //"diss-t2-tsd1-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t2-tsd1-cupid",task_name:"Treatment Session 1 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        "deq-t3-tsd1-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t3-tsd1-cupid",form_module:"deq-t3-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t3-tsd1-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t3-tsd1-cupid",task_name:"Treatment Session 1 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t4-tsd1-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t4-tsd1-cupid",form_module:"deq-t4-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Drug Effects Questionnaire (DEQ) (T4: Pre-Discharge)"},
        "deq-t4-tsd1-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t4-tsd1-cupid",task_name:"Treatment Session 1 – Day - Drug Effects Questionnaire (DEQ) (T4: Pre-Discharge)"},
        "poms-t3-tsd1-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t3-tsd1-cupid",form_module:"poms-t3-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Abbreviated Profile of Mood States (POMS) (T3: Morning)"},
        "poms-t3-tsd1-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t3-tsd1-cupid",task_name:"Treatment Session 1 – Day - Abbreviated Profile of Mood States (POMS) (T3: Morning)"},
        "poms-t4-tsd1-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t4-tsd1-cupid",form_module:"poms-t4-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "poms-t4-tsd1-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t4-tsd1-cupid",task_name:"Treatment Session 1 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "pvt-t1-tsd1-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t1-tsd1-cupid",form_module:"pvt-t1-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t1-tsd1-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t1-tsd1-cupid",task_name:"Treatment Session 1 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t2-tsd1-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t2-tsd1-cupid",form_module:"pvt-t2-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        "pvt-t2-tsd1-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t2-tsd1-cupid",task_name:"Treatment Session 1 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        //"drug-admin-tsd1-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsd1-cupid",form_module:"drug-admin-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Time drug administration and biological collections"},
        //"drug-admin-tsd1-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsd1-cupid",task_name:"Treatment Session 1 – Day - Time drug administration and biological collections"},
        "word-pairs-tsd1-data-cupid":                {url:"$H/m/library/word-pairs-data.html",Table:"word-pairs-tsd1-cupid",form_module:"word-pairs-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Word Pairs Data Entry"},
        "word-pairs-tsd1-form-cupid":                {url:"$H/m/library/word-pairs-form.html",Table:"word-pairs-tsd1-cupid",task_name:"Treatment Session 1 – Day - Word Pairs Data Entry"},
        "post-finger-tapping-tsd1-data-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"post-finger-tapping-tsd1-cupid",form_module:"post-finger-tapping-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Finger Tapping"},
        "post-finger-tapping-tsd1-form-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"post-finger-tapping-tsd1-cupid",task_name:"Treatment Session 1 – Day - Finger Tapping"},
        "adverse-event-symptoms-tsd1-data-cupid":                {url:"$H/m/library/adverse-event-symptoms-data.html",Table:"adverse-event-symptoms-tsd1-cupid",form_module:"adverse-event-symptoms-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Adverse Event Symptom"},
        "adverse-event-symptoms-tsd1-form-cupid":                {url:"$H/m/library/adverse-event-symptoms-form.html",Table:"adverse-event-symptoms-tsd1-cupid",task_name:"Treatment Session 1 – Day - Adverse Event Symptom"},
        "participant-expectation-tsd1-data-cupid":                {url:"$H/m/library/participant-expectation-data.html",Table:"participant-expectation-tsd1-cupid",form_module:"participant-expectation-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Participant Expectation"},
        "participant-expectation-tsd1-form-cupid":                {url:"$H/m/library/participant-expectation-form.html",Table:"participant-expectation-tsd1-cupid",task_name:"Treatment Session 1 – Day - Participant Expectation"},
        "sds-t3-tsd1-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t3-tsd1-cupid",form_module:"sds-t3-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t3-tsd1-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t3-tsd1-cupid",task_name:"Treatment Session 1 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t4-tsd1-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t4-tsd1-cupid",form_module:"sds-t4-tsd1-form-cupid",task_name:"Treatment Session 1 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},
        "sds-t4-tsd1-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t4-tsd1-cupid",task_name:"Treatment Session 1 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},

        "fu-call1-tsf1-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call1-tsf1-cupid",form_module:"fu-call1-tsf1-form-cupid",task_name:"Treatment Session 1 – Follow-up - Follow up call 1"},
        "fu-call1-tsf1-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call1-tsf1-cupid",task_name:"Treatment Session 1 – Follow-up - Follow up call 1"},
        "fu-call2-tsf1-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call2-tsf1-cupid",form_module:"fu-call2-tsf1-form-cupid",task_name:"Treatment Session 1 – Follow-up - Follow up call 2"},
        "fu-call2-tsf1-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call2-tsf1-cupid",task_name:"Treatment Session 1 – Follow-up - Follow up call 2"},
//Session 2
        "ksd-pts2-data-cupid":                {url:"$H/m/library/ksd-data.html",Table:"ksd-pts2-cupid",form_module:"ksd-pts2-form-cupid",task_name:"Pre-Treatment Session 2 - Karolinska Sleep Diary"},
        "ksd-pts2-form-cupid":                {url:"$H/m/library/ksd-form.html",Table:"ksd-pts2-cupid",task_name:"Pre-Treatment Session 2 - Karolinska Sleep Diary"},
        "actigraphy-pts2-data-cupid":                {url:"$H/m/library/actigraphy-data.html",Table:"actigraphy-pts2-cupid",form_module:"actigraphy-pts2-form-cupid",task_name:"Pre-Treatment Session 2 - Actigraphy data/report"},
        "actigraphy-pts2-form-cupid":                {url:"$H/m/library/actigraphy-form.html",Table:"actigraphy-pts2-cupid",task_name:"Pre-Treatment Session 2 - Actigraphy data/report"},

        "date-tsn2-data-cupid":                {url:"$H/m/library/date-data.html",Table:"date-tsn2-cupid",form_module:"date-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Visit Date"},
        "date-tsn2-form-cupid":                {url:"$H/m/library/date-form.html",Table:"date-tsn2-cupid",task_name:"Treatment Session 2 – Night - Visit Date"},
        "bms-tsn2-data-cupid":                {url:"$H/m/library/bms-data.html",Table:"bms-tsn2-cupid",form_module:"bms-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Brief Medical Screen"},
        "bms-tsn2-form-cupid":                {url:"$H/m/library/bms-form.html",Table:"bms-tsn2-cupid",task_name:"Treatment Session 2 – Night - Brief Medical Screen"},
        "drug-admin-tsn2-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsn2-cupid",form_module:"drug-admin-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Time drug administration and biological collections"},
        "drug-admin-tsn2-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsn2-cupid",task_name:"Treatment Session 2 – Night - Time drug administration and biological collections"},
        "pre-finger-tapping-tsn2-data-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"pre-finger-tapping-tsn2-cupid",form_module:"pre-finger-tapping-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Finger Tapping"},
        "pre-finger-tapping-tsn2-form-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"pre-finger-tapping-tsn2-cupid",task_name:"Treatment Session 2 – Night - Finger Tapping"},
        "poms-t1-tsn2-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t1-tsn2-cupid",form_module:"poms-t1-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t1-tsn2-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t1-tsn2-cupid",task_name:"Treatment Session 2 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t2-tsn2-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t2-tsn2-cupid",form_module:"poms-t2-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "poms-t2-tsn2-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t2-tsn2-cupid",task_name:"Treatment Session 2 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "deq-t1-tsn2-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t1-tsn2-cupid",form_module:"deq-t1-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Drug Effects Questionnaire (DEQ)  (T1: Baseline)"},
        "deq-t1-tsn2-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t1-tsn2-cupid",task_name:"Treatment Session 2 – Night - Drug Effects Questionnaire (DEQ) (T1: Baseline)"},
        "deq-t2-tsn2-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t2-tsn2-cupid",form_module:"deq-t2-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "deq-t2-tsn2-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t2-tsn2-cupid",task_name:"Treatment Session 2 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "posture-t1-tsn2-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t1-tsn2-cupid",form_module:"posture-t1-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Posturography (T1: Baseline)"},
        "posture-t1-tsn2-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t1-tsn2-cupid",task_name:"Treatment Session 2 – Night - Posturography (T1: Baseline)"},
        "posture-t2-tsn2-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t2-tsn2-cupid",form_module:"posture-t2-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Posturography (T2: Post Drug Administration)"},
        "posture-t2-tsn2-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t2-tsn2-cupid",task_name:"Treatment Session 2 – Night - Posturography (T2: Post Drug Administration)"},
        "kss-tsn2-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsn2-cupid",form_module:"kss-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsn2-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsn2-cupid",task_name:"Treatment Session 2 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kdt-tsn2-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsn2-cupid",form_module:"kdt-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsn2-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsn2-cupid",task_name:"Treatment Session 2 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "psg-tsn2-data-cupid":                {url:"$H/m/library/psg-data.html",Table:"psg-tsn2-cupid",form_module:"psg-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Polysomnography (PSG) report"},
        "psg-tsn2-form-cupid":                {url:"$H/m/library/psg-form.html",Table:"psg-tsn2-cupid",task_name:"Treatment Session 2 – Night - Polysomnography (PSG) report"},
        "uds-tsn2-data-cupid":                {url:"$H/m/library/uds-data.html",Table:"uds-tsn2-cupid",form_module:"uds-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Urinary drug screen (UDS)"},
        "uds-tsn2-form-cupid":                {url:"$H/m/library/uds-form.html",Table:"uds-tsn2-cupid",task_name:"Treatment Session 2 – Night - Urinary drug screen (UDS)"},
        "sds-t1-tsn2-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t1-tsn2-cupid",form_module:"sds-t1-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t1-tsn2-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t1-tsn2-cupid",task_name:"Treatment Session 2 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t2-tsn2-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t2-tsn2-cupid",form_module:"sds-t2-tsn2-form-cupid",task_name:"Treatment Session 2 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},
        "sds-t2-tsn2-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t2-tsn2-cupid",task_name:"Treatment Session 2 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},

        "kdt-tsd2-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsd2-cupid",form_module:"kdt-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsd2-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsd2-cupid",task_name:"Treatment Session 2 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kss-tsd2-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsd2-cupid",form_module:"kss-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsd2-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsd2-cupid",task_name:"Treatment Session 2 – Day - Karolinska Sleepiness Scale (KSS)"},
        "driving-tsd2-data-cupid":                {url:"$H/m/library/driving-data.html",Table:"driving-tsd2-cupid",form_module:"driving-tsd2-form-cupid",task_name:"Treatment Session 2 – Day -Driving Simulation Report Upload"},
        "driving-tsd2-form-cupid":                {url:"$H/m/library/driving-form.html",Table:"driving-tsd2-cupid",task_name:"Treatment Session 2 – Day - Driving Simulation Report Upload"},
        "posture-t3-tsd2-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t3-tsd2-cupid",form_module:"posture-t3-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Posturography (T3: Upo Wake)"},
        "posture-t3-tsd2-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t3-tsd2-cupid",task_name:"Treatment Session 2 – Day - Posturography (T3: Upo Wake)"},
        "lseq-tsd2-data-cupid":                {url:"$H/m/library/lseq-data.html",Table:"lseq-tsd2-cupid",form_module:"lseq-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "lseq-tsd2-form-cupid":                {url:"$H/m/library/lseq-form.html",Table:"lseq-tsd2-cupid",task_name:"Treatment Session 2 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "rcsq-tsd2-data-cupid":                {url:"$H/m/library/rcsq-data.html",Table:"rcsq-tsd2-cupid",form_module:"rcsq-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        "rcsq-tsd2-form-cupid":                {url:"$H/m/library/rcsq-form.html",Table:"rcsq-tsd2-cupid",task_name:"Treatment Session 2 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        //"diss-t1-tsd2-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t1-tsd2-cupid",form_module:"diss-t1-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t1-tsd2-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t1-tsd2-cupid",task_name:"Treatment Session 2 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t2-tsd2-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t2-tsd2-cupid",form_module:"diss-t2-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        //"diss-t2-tsd2-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t2-tsd2-cupid",task_name:"Treatment Session 2 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        "deq-t3-tsd2-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t3-tsd2-cupid",form_module:"deq-t3-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t3-tsd2-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t3-tsd2-cupid",task_name:"Treatment Session 2 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t4-tsd2-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t4-tsd2-cupid",form_module:"deq-t4-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Drug Effects Questionnaire (DEQ)  (T4: Pre-Discharge)"},
        "deq-t4-tsd2-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t4-tsd2-cupid",task_name:"Treatment Session 2 – Day - Drug Effects Questionnaire (DEQ) (T4: Pre-Discharge)"},
        "poms-t3-tsd2-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t3-tsd2-cupid",form_module:"poms-t3-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Abbreviated Profile of Mood States (POMS) (T3: Morning)"},
        "poms-t3-tsd2-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t3-tsd2-cupid",task_name:"Treatment Session 2 – Day - Abbreviated Profile of Mood States (POMS) (T3: Mid Morning)"},
        "poms-t4-tsd2-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t4-tsd2-cupid",form_module:"poms-t4-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "poms-t4-tsd2-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t4-tsd2-cupid",task_name:"Treatment Session 2 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "pvt-t1-tsd2-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t1-tsd2-cupid",form_module:"pvt-t1-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t1-tsd2-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t1-tsd2-cupid",task_name:"Treatment Session 2 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t2-tsd2-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t2-tsd2-cupid",form_module:"pvt-t2-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        "pvt-t2-tsd2-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t2-tsd2-cupid",task_name:"Treatment Session 2 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        //"drug-admin-tsd2-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsd2-cupid",form_module:"drug-admin-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Time drug administration and biological collections"},
        //"drug-admin-tsd2-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsd2-cupid",task_name:"Treatment Session 2 – Day - Time drug administration and biological collections"},
        "word-pairs-tsd2-data-cupid":                {url:"$H/m/library/word-pairs-data.html",Table:"word-pairs-tsd2-cupid",form_module:"word-pairs-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Word Pairs Data Entry"},
        "word-pairs-tsd2-form-cupid":                {url:"$H/m/library/word-pairs-form.html",Table:"word-pairs-tsd2-cupid",task_name:"Treatment Session 2 – Day - Word Pairs Data Entry"},
        "post-finger-tapping-tsd2-data-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"post-finger-tapping-tsd2-cupid",form_module:"post-finger-tapping-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Finger Tapping"},
        "post-finger-tapping-tsd2-form-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"post-finger-tapping-tsd2-cupid",task_name:"Treatment Session 2 – Day - Finger Tapping"},
        "adverse-event-symptoms-tsd2-data-cupid":                {url:"$H/m/library/adverse-event-symptoms-data.html",Table:"adverse-event-symptoms-tsd2-cupid",form_module:"adverse-event-symptoms-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Adverse Event Symptom"},
        "adverse-event-symptoms-tsd2-form-cupid":                {url:"$H/m/library/adverse-event-symptoms-form.html",Table:"adverse-event-symptoms-tsd2-cupid",task_name:"Treatment Session 2 – Day - Adverse Event Symptom"},
        "participant-expectation-tsd2-data-cupid":                {url:"$H/m/library/participant-expectation-data.html",Table:"participant-expectation-tsd2-cupid",form_module:"participant-expectation-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Participant Expectation"},
        "participant-expectation-tsd2-form-cupid":                {url:"$H/m/library/participant-expectation-form.html",Table:"participant-expectation-tsd2-cupid",task_name:"Treatment Session 2 – Day - Participant Expectation"},
        "sds-t3-tsd2-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t3-tsd2-cupid",form_module:"sds-t3-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t3-tsd2-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t3-tsd2-cupid",task_name:"Treatment Session 2 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t4-tsd2-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t4-tsd2-cupid",form_module:"sds-t4-tsd2-form-cupid",task_name:"Treatment Session 2 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},
        "sds-t4-tsd2-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t4-tsd2-cupid",task_name:"Treatment Session 2 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},

        "fu-call1-tsf2-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call1-tsf2-cupid",form_module:"fu-call1-tsf2-form-cupid",task_name:"Treatment Session 2 – Follow-up - Follow up call 1"},
        "fu-call1-tsf2-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call1-tsf2-cupid",task_name:"Treatment Session 2 – Follow-up - Follow up call 1"},
        "fu-call2-tsf2-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call2-tsf2-cupid",form_module:"fu-call2-tsf2-form-cupid",task_name:"Treatment Session 2 – Follow-up - Follow up call 2"},
        "fu-call2-tsf2-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call2-tsf2-cupid",task_name:"Treatment Session 2 – Follow-up - Follow up call 2"},
//Session 3
        "ksd-pts3-data-cupid":                {url:"$H/m/library/ksd-data.html",Table:"ksd-pts3-cupid",form_module:"ksd-pts3-form-cupid",task_name:"Pre-Treatment Session 3 - Karolinska Sleep Diary"},
        "ksd-pts3-form-cupid":                {url:"$H/m/library/ksd-form.html",Table:"ksd-pts3-cupid",task_name:"Pre-Treatment Session 3 - Karolinska Sleep Diary"},
        "actigraphy-pts3-data-cupid":                {url:"$H/m/library/actigraphy-data.html",Table:"actigraphy-pts3-cupid",form_module:"actigraphy-pts3-form-cupid",task_name:"Pre-Treatment Session 3 - Actigraphy data/report"},
        "actigraphy-pts3-form-cupid":                {url:"$H/m/library/actigraphy-form.html",Table:"actigraphy-pts3-cupid",task_name:"Pre-Treatment Session 3 - Actigraphy data/report"},

        "date-tsn3-data-cupid":                {url:"$H/m/library/date-data.html",Table:"date-tsn3-cupid",form_module:"date-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Visit Date"},
        "date-tsn3-form-cupid":                {url:"$H/m/library/date-form.html",Table:"date-tsn3-cupid",task_name:"Treatment Session 3 – Night - Visit Date"},
        "bms-tsn3-data-cupid":                {url:"$H/m/library/bms-data.html",Table:"bms-tsn3-cupid",form_module:"bms-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Brief Medical Screen"},
        "bms-tsn3-form-cupid":                {url:"$H/m/library/bms-form.html",Table:"bms-tsn3-cupid",task_name:"Treatment Session 3 – Night - Brief Medical Screen"},
        "drug-admin-tsn3-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsn3-cupid",form_module:"drug-admin-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Time drug administration and biological collections"},
        "drug-admin-tsn3-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsn3-cupid",task_name:"Treatment Session 3 – Night - Time drug administration and biological collections"},
        "word-pairs-pre-set3t2-tsn1-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-trial2.html",task_name:"Treatment Session 1 – Night - Word pairs Set 3 Trial 2"},
        "word-pairs-pre-set3t3-tsn1-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-trial3.html",task_name:"Treatment Session 1 – Night - Word pairs Set 3 Trial 3"},
        "pre-finger-tapping-tsn3-data-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"pre-finger-tapping-tsn3-cupid",form_module:"pre-finger-tapping-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Finger Tapping"},
        "pre-finger-tapping-tsn3-form-cupid":                {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"pre-finger-tapping-tsn3-cupid",task_name:"Treatment Session 3 – Night - Finger Tapping"},
        "poms-t1-tsn3-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t1-tsn3-cupid",form_module:"poms-t1-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t1-tsn3-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t1-tsn3-cupid",task_name:"Treatment Session 3 – Night - Abbreviated Profile of Mood States (POMS) (T1: Baseline)"},
        "poms-t2-tsn3-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t2-tsn3-cupid",form_module:"poms-t2-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "poms-t2-tsn3-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t2-tsn3-cupid",task_name:"Treatment Session 3 – Night - Abbreviated Profile of Mood States (POMS) (T2: Post Drug Administration)"},
        "deq-t1-tsn3-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t1-tsn3-cupid",form_module:"deq-t1-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Drug Effects Questionnaire (DEQ)  (T1: Baseline)"},
        "deq-t1-tsn3-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t1-tsn3-cupid",task_name:"Treatment Session 3 – Night - Drug Effects Questionnaire (DEQ) (T1: Baseline)"},
        "deq-t2-tsn3-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t2-tsn3-cupid",form_module:"deq-t2-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "deq-t2-tsn3-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t2-tsn3-cupid",task_name:"Treatment Session 3 – Night - Drug Effects Questionnaire (DEQ) (T2: Post Drug Administration)"},
        "posture-t1-tsn3-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t1-tsn3-cupid",form_module:"posture-t1-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Posturography (T1: Baseline)"},
        "posture-t1-tsn3-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t1-tsn3-cupid",task_name:"Treatment Session 3 – Night - Posturography (T1: Baseline)"},
        "posture-t2-tsn3-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t2-tsn3-cupid",form_module:"posture-t2-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Posturography (T2: Post Drug Administration)"},
        "posture-t2-tsn3-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t2-tsn3-cupid",task_name:"Treatment Session 3 – Night - Posturography (T2: Post Drug Administration)"},
        "kss-tsn3-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsn3-cupid",form_module:"kss-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsn3-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsn3-cupid",task_name:"Treatment Session 3 – Night - Karolinska Sleepiness Scale (KSS)"},
        "kdt-tsn3-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsn3-cupid",form_module:"kdt-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsn3-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsn3-cupid",task_name:"Treatment Session 3 – Night - Karolinska Drowsiness test (KDT) with EEG"},
        "psg-tsn3-data-cupid":                {url:"$H/m/library/psg-data.html",Table:"psg-tsn3-cupid",form_module:"psg-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Polysomnography (PSG) report"},
        "psg-tsn3-form-cupid":                {url:"$H/m/library/psg-form.html",Table:"psg-tsn3-cupid",task_name:"Treatment Session 3 – Night - Polysomnography (PSG) report"},
        "uds-tsn3-data-cupid":                {url:"$H/m/library/uds-data.html",Table:"uds-tsn3-cupid",form_module:"uds-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Urinary drug screen (UDS)"},
        "uds-tsn3-form-cupid":                {url:"$H/m/library/uds-form.html",Table:"uds-tsn3-cupid",task_name:"Treatment Session 3 – Night - Urinary drug screen (UDS)"},
        "sds-t1-tsn3-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t1-tsn3-cupid",form_module:"sds-t1-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t1-tsn3-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t1-tsn3-cupid",task_name:"Treatment Session 3 – Night - Salivary Drug Screen (T1: Baseline)"},
        "sds-t2-tsn3-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t2-tsn3-cupid",form_module:"sds-t2-tsn3-form-cupid",task_name:"Treatment Session 3 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},
        "sds-t2-tsn3-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t2-tsn3-cupid",task_name:"Treatment Session 3 – Night - Salivary Drug Screen (T2: Post Drug Administration)"},

        "kdt-tsd3-data-cupid":                {url:"$H/m/library/kdt-data.html",Table:"kdt-tsd3-cupid",form_module:"kdt-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kdt-tsd3-form-cupid":                {url:"$H/m/library/kdt-form.html",Table:"kdt-tsd3-cupid",task_name:"Treatment Session 3 – Day - Karolinska Drowsiness test (KDT) with EEG"},
        "kss-tsd3-data-cupid":                {url:"$H/m/library/kss-data.html",Table:"kss-tsd3-cupid",form_module:"kss-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Karolinska Sleepiness Scale (KSS)"},
        "kss-tsd3-form-cupid":                {url:"$H/m/library/kss-form.html",Table:"kss-tsd3-cupid",task_name:"Treatment Session 3 – Day - Karolinska Sleepiness Scale (KSS)"},
        "driving-tsd3-data-cupid":                {url:"$H/m/library/driving-data.html",Table:"driving-tsd3-cupid",form_module:"driving-tsd3-form-cupid",task_name:"Treatment Session 3 – Day -Driving Simulation Report Upload"},
        "driving-tsd3-form-cupid":                {url:"$H/m/library/driving-form.html",Table:"driving-tsd3-cupid",task_name:"Treatment Session 3 – Day - Driving Simulation Report Upload"},
        "posture-t3-tsd3-data-cupid":                {url:"$H/m/library/posture-data.html",Table:"posture-t3-tsd3-cupid",form_module:"posture-t3-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Posturography (T3: Upo Wake)"},
        "posture-t3-tsd3-form-cupid":                {url:"$H/m/library/posture-form.html",Table:"posture-t3-tsd3-cupid",task_name:"Treatment Session 3 – Day - Posturography (T3: Upo Wake)"},
        "lseq-tsd3-data-cupid":                {url:"$H/m/library/lseq-data.html",Table:"lseq-tsd3-cupid",form_module:"lseq-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "lseq-tsd3-form-cupid":                {url:"$H/m/library/lseq-form.html",Table:"lseq-tsd3-cupid",task_name:"Treatment Session 3 – Day - Leeds Sleep Evaluation Questionnaire (LSEQ)"},
        "rcsq-tsd3-data-cupid":                {url:"$H/m/library/rcsq-data.html",Table:"rcsq-tsd3-cupid",form_module:"rcsq-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        "rcsq-tsd3-form-cupid":                {url:"$H/m/library/rcsq-form.html",Table:"rcsq-tsd3-cupid",task_name:"Treatment Session 3 – Day - Richards Campbell Sleep Questionnaire (RCSQ)"},
        //"diss-t1-tsd3-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t1-tsd3-cupid",form_module:"diss-t1-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t1-tsd3-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t1-tsd3-cupid",task_name:"Treatment Session 3 – Day - Daytime Insomnia Symptom Scale (DISS) (T1: Morning 1)"},
        //"diss-t2-tsd3-data-cupid":                {url:"$H/m/library/diss-data.html",Table:"diss-t2-tsd3-cupid",form_module:"diss-t2-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        //"diss-t2-tsd3-form-cupid":                {url:"$H/m/library/diss-form.html",Table:"diss-t2-tsd3-cupid",task_name:"Treatment Session 3 – Day - Daytime Insomnia Symptom Scale (DISS) (T2: Morning 1)"},
        "deq-t3-tsd3-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t3-tsd3-cupid",form_module:"deq-t3-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t3-tsd3-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t3-tsd3-cupid",task_name:"Treatment Session 3 – Day - Drug Effects Questionnaire (DEQ) (T3: Morning)"},
        "deq-t4-tsd3-data-cupid":                {url:"$H/m/library/deq-data.html",Table:"deq-t4-tsd3-cupid",form_module:"deq-t4-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Drug Effects Questionnaire (DEQ)  (T4: Pre-Discharge)"},
        "deq-t4-tsd3-form-cupid":                {url:"$H/m/library/deq-form.html",Table:"deq-t4-tsd3-cupid",task_name:"Treatment Session 3 – Day - Drug Effects Questionnaire (DEQ) (T4: Pre-Discharge)"},
        "poms-t3-tsd3-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t3-tsd3-cupid",form_module:"poms-t3-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Abbreviated Profile of Mood States (POMS) (T3: Morning)"},
        "poms-t3-tsd3-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t3-tsd3-cupid",task_name:"Treatment Session 3 – Day - Abbreviated Profile of Mood States (POMS) (T3: Mid Morning)"},
        "poms-t4-tsd3-data-cupid":                {url:"$H/m/library/poms-data.html",Table:"poms-t4-tsd3-cupid",form_module:"poms-t4-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "poms-t4-tsd3-form-cupid":                {url:"$H/m/library/poms-form.html",Table:"poms-t4-tsd3-cupid",task_name:"Treatment Session 3 – Day - Abbreviated Profile of Mood States (POMS) (T4: Pre-Discharge)"},
        "pvt-t1-tsd3-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t1-tsd3-cupid",form_module:"pvt-t1-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t1-tsd3-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t1-tsd3-cupid",task_name:"Treatment Session 3 – Day - Psychomotor Vigilance Test (T1: Morning 1)"},
        "pvt-t2-tsd3-data-cupid":                {url:"$H/m/library/pvt-data.html",Table:"pvt-t2-tsd3-cupid",form_module:"pvt-t2-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        "pvt-t2-tsd3-form-cupid":                {url:"$H/m/library/pvt-form.html",Table:"pvt-t2-tsd3-cupid",task_name:"Treatment Session 3 – Day - Psychomotor Vigilance Test (T2: Morning 1)"},
        //"drug-admin-tsd3-data-cupid":                {url:"$H/m/library/drug-admin-data.html",Table:"drug-admin-tsd3-cupid",form_module:"drug-admin-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Time drug administration and biological collections"},
        //"drug-admin-tsd3-form-cupid":                {url:"$H/m/library/drug-admin-form.html",Table:"drug-admin-tsd3-cupid",task_name:"Treatment Session 3 – Day - Time drug administration and biological collections"},
        "word-pairs-tsd3-data-cupid":                {url:"$H/m/library/word-pairs-data.html",Table:"word-pairs-tsd3-cupid",form_module:"word-pairs-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Word Pairs Data Entry"},
        "word-pairs-tsd3-form-cupid":                {url:"$H/m/library/word-pairs-form.html",Table:"word-pairs-tsd3-cupid",task_name:"Treatment Session 3 – Day - Word Pairs Data Entry"},
        "post-finger-tapping-tsd3-data-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"post-finger-tapping-tsd3-cupid",form_module:"post-finger-tapping-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Finger Tapping"},
        "post-finger-tapping-tsd3-form-cupid":                {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"post-finger-tapping-tsd3-cupid",task_name:"Treatment Session 3 – Day - Finger Tapping"},
        "adverse-event-symptoms-tsd3-data-cupid":                {url:"$H/m/library/adverse-event-symptoms-data.html",Table:"adverse-event-symptoms-tsd3-cupid",form_module:"adverse-event-symptoms-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Adverse Event Symptom"},
        "adverse-event-symptoms-tsd3-form-cupid":                {url:"$H/m/library/adverse-event-symptoms-form.html",Table:"adverse-event-symptoms-tsd3-cupid",task_name:"Treatment Session 3 – Day - Adverse Event Symptom"},
        "participant-expectation-tsd3-data-cupid":                {url:"$H/m/library/participant-expectation-data.html",Table:"participant-expectation-tsd3-cupid",form_module:"participant-expectation-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Participant Expectation"},
        "participant-expectation-tsd3-form-cupid":                {url:"$H/m/library/participant-expectation-form.html",Table:"participant-expectation-tsd3-cupid",task_name:"Treatment Session 3 – Day - Participant Expectation"},
        "sds-t3-tsd3-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t3-tsd3-cupid",form_module:"sds-t3-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t3-tsd3-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t3-tsd3-cupid",task_name:"Treatment Session 3 – Day - Salivary Drug Screen (T3: Upon Wake)"},
        "sds-t4-tsd3-data-cupid":                {url:"$H/m/library/sdrugs-data.html",Table:"sds-t4-tsd3-cupid",form_module:"sds-t4-tsd3-form-cupid",task_name:"Treatment Session 3 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},
        "sds-t4-tsd3-form-cupid":                {url:"$H/m/library/sdrugs-form.html",Table:"sds-t4-tsd3-cupid",task_name:"Treatment Session 3 – Day - Salivary Drug Screen (T4: Pre-Discharge)"},

        "fu-call1-tsf3-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call1-tsf3-cupid",form_module:"fu-call1-tsf3-form-cupid",task_name:"Treatment Session 3 – Follow-up - Follow up call 1"},
        "fu-call1-tsf3-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call1-tsf3-cupid",task_name:"Treatment Session 3 – Follow-up - Follow up call 1"},
        "fu-call2-tsf3-data-cupid":                {url:"$H/m/library/fu-call-data.html",Table:"fu-call2-tsf3-cupid",form_module:"fu-call2-tsf3-form-cupid",task_name:"Treatment Session 3 – Follow-up - Follow up call 2"},
        "fu-call2-tsf3-form-cupid":                {url:"$H/m/library/fu-call-form.html",Table:"fu-call2-tsf3-cupid",task_name:"Treatment Session 3 – Follow-up - Follow up call 2"},
        // Word pairs
        "word-pairs-pre-t1-set1-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set1-trial1.html"},
        "word-pairs-pre-t2-set1-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set1-trial2.html"},
        "word-pairs-pre-t3-set1-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set1-trial3.html"},
        "word-pairs-post-tt-set1-cupid":	    {url:"$H/m/word-pairs/morning-wordpairs-set1.html"},
        "word-pairs-pre-t1-set2-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set2-trial1.html"},
        "word-pairs-pre-t2-set2-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set2-trial2.html"},
        "word-pairs-pre-t3-set2-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set2-trial3.html"},
        "word-pairs-post-tt-set2-cupid":	    {url:"$H/m/word-pairs/morning-wordpairs-set2.html"},
        "word-pairs-pre-t1-set3-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-trial1.html"},
        "word-pairs-pre-t2-set3-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-trial2.html"},
        "word-pairs-pre-t3-set3-cupid":	    {url:"$H/m/word-pairs/evening-wordpairs-set3-trial3.html"},
        "word-pairs-post-tt-set3-cupid":	    {url:"$H/m/word-pairs/morning-wordpairs-set3.html"},
    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    //if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
    //}

})();
